### ISSUE TITLE
Transaction Reference Number is not returned by the parser

### ISSUE THREAD

**Issue by denisld** [wolph/mt940#102]
The Transaction object does not contain the mandatory SWIFT Transaction Reference Number (Tag :20:).  It only includes the field called 'bank_reference', which appears to be extracted from the section with Tag :61:. These two numbers are not the same, and I would imagine many users require at least the Tag 20 entry.

**Comment by wolph** [comment]
There should be a `transaction_reference` available for a `:20:`: https://github.com/wolph/mt940/blob/2b8b86586247d4b391e523aa6f7ff44f4c79b200/mt940/tags.py#L135

We can see an example with this sta file here:
https://github.com/wolph/mt940/blob/2b8b86586247d4b391e523aa6f7ff44f4c79b200/mt940_tests/self-provided/transaction_details_wrapped.sta#L2

Which generates this data:
https://github.com/wolph/mt940/blob/2b8b86586247d4b391e523aa6f7ff44f4c79b200/mt940_tests/self-provided/transaction_details_wrapped.yml#L24

Do you have a specific example where this is not working?

**Comment by mmdevl** [comment]
You can find the transaction reference as follow:
```
transactions = mt940.parse('test.sta')
print(transactions.data['transaction_reference'])
```

But for instance my bank exports several transaction references at the same time (one for each account). And with the `print` above you would get only the last transaction reference.

Try with this example:

```
:20:STARTUMSE
:25:12345678/1020304050
:28C:00000/001
:60F:C160229EUR1200,00
:61:1602300301DR6,00N024NONREF
:86:805?00ENTGELTABSCHLUSS?106666?20Pauschalen?3012345678?1122334
45566?602017-01-01T13
:12:11
:62F:C160301EUR1194,00
:20:STARTUMSE2
:25:12345678/1020304050
:28C:00000/001
:60F:C160229EUR1200,00
:61:1602300301DR6,00N024NONREF
:86:805?00ENTGELTABSCHLUSS?106666?20Pauschalen?3012345678?1122334
45566?602017-01-01T13
:12:11
:62F:C160301EUR1194,00
```
I think this is a bug and I see 2 solutions:

1. add a 'transaction_reference' key to every transaction objects or
2. group the objects by 'transaction_reference'

**Comment by wolph** [comment]
You're right. For some files this is indeed not a usable situation. Option 2 is quite involved so I've opted for adding a transformer to take care of option 1. I'm still finalizing the code so the tests keep on working without issues but the current develop branch shows the new behaviour.

**Comment by wolph** [comment]
The new release is online. Every transaction should have the relevant `transaction_reference` now. If you want to add more fields you can do so using the post processors: https://github.com/wolph/mt940/blob/develop/mt940/models.py#L266

**Comment by aGitForEveryone** [comment]
Amazing fix! This same issue happens when a single mt940 file contains transactions for several bank accounts. The `account_identification` field in `transactions.data` would have the value of the last `tag 25`. So it was impossible to track after transaction parsing what bank account the transaction belonged to. 

I implemented a more complex workaround to separate the transactions per bank account. But with this post processor, it's possible to include that information in the transaction data itself. So the parsing becomes much easier.

Now don't forget that the global `transactions.data` gets overwritten with each new transaction, otherwise this feature doesn't work anymore.
