### ISSUE TITLE
ImportError: cannot import name 'parse'

### ISSUE THREAD

**Issue by spoetnik** [WoLpH/mt940#3]
After a  pip install mt-940 I get error;
    importError: cannot import name 'parse'

Using Python 3.4.2
Any ideas?

**Comment by WoLpH** [comment]
It's a python 3.4 thing, easy to fix luckily :)

The new version (919710b37e801ff1020def54ac6f241e57e66a17) supports python 3.4 as well.

**Comment by spoetnik** [comment]
Successfully installed mt-940
Thanks! (Dank je wel!)

**Comment by SlimSchip** [comment]
Same issue with laster (Master and develop branche)

Traceback (most recent call last):
  File "/Users/martijn/Documents/mt940.py", line 1, in <module>
    import mt940
  File "/Users/martijn/Documents/mt940.py", line 4, in <module>
    transactions = mt940.parse('~/Downloads/NL64INGB0008766989_01-01-2019_31-12-2019.940')
AttributeError: partially initialized module 'mt940' has no attribute 'parse' (most likely due to a circular import)

on both Python (MacBook) 3.10.6 and Debian 3.9. installed with pip and with setup.py master and development branches

any tips on how to solve this?

M

**Comment by wolph** [comment]
The problem is that your testfile is named mt940.py so it's importing
itself. You need to rename both the mt940.py and the mt940.pyc (if the
latter exists)

**Comment by SlimSchip** [comment]
Owww … how stupid can one be ...
