### ISSUE TITLE
Fault tollerancy of a parser.

### ISSUE THREAD

**Issue by wieslawmlynarski** [WoLpH/mt940#44]
Hi, I was testing the library for some of the turkish bank.
The problem with them is that that they a not really well formed (according to the standard). 
Many banks, in general, don't really follow well the standard.
I was wondering if I can work on making a PR which makes the parser more fault-tolerant?
So the parser will give his best effort to parse the entry, but if it fails it does not return an error just the fields which it was able to parse.
One of the examples of best effort when one of the "mandatory" fields Is missing like field  28C ("Statement Number/Sequence Number").

**Comment by WoLpH** [comment]
The parser is meant to be pretty fault-tolerant but it can indeed still fail in some cases.
Pull requests are always welcome and assuming it passes all tests merged as soon as possible :)

I should note that the current develop branch is slightly broken due to a previous pull request and I'm still working on fixing that (I just got back from holiday so... hopefully soon). For the time being I would recommend basing your pull request on the master branch, the only difference is that slightly broken pull request anyhow.

**Comment by WoLpH** [comment]
I've pushed out a new release and fixed all issues with the develop branch so if you're working on a pull request it might be best to merge in the latest changes :)

**Comment by wieslawmlynarski** [comment]
Hey,
I plan to work on this topic using examples from my company. But maybe till then this issue can be closed.
