### ISSUE TITLE
Newline not recognized

### ISSUE THREAD

**Issue by mncoon** [WoLpH/mt940#62]
Hi!

On trying to import from a german Bank called Sparkasse I have the problem that it looks like a new-line character is not recognized. This is the error:

```
  File "/usr/local/lib/python3.5/dist-packages/mt940/tags.py", line 84, in parse
    self, value)
RuntimeError: ('Unable to parse "<mt940.tags.StatementNumber object at 0x7fa570515a58>" from "00000/002\n:60M"', <mt940.tags.StatementNumber object at 0x7fa570515a58>, '00000/002\n:60M')
```

Have you had this in the past? Is there a way to solve it, or is this a problem of the bank?

Update:
It is a file with many transactions and it looks like, the bank is splitting it in various StatementNumbers:

```
:20:STARTUMSE
:25:44550045/0000177352
:28C:00000/001
.......
-
:20:STARTUMSE
:25:44550045/0000177352
:28C:00000/002
........
```

**Comment by WoLpH** [comment]
With a tiny bit more verbose logging it's easier to see what's going on here:

![image](https://user-images.githubusercontent.com/270571/41457245-57076784-7083-11e8-8122-cd28e8c4bbbf.png)


And the problem is not in the newline but it's with the `.......`. It's not recognizing that as a statement so it's retrying by appending it to the previous statement.

If we change the sample like this, it will work:
```
:20:STARTUMSE
:25:44550045/0000177352
:28C:00000/001
-
:20:STARTUMSE
:25:44550045/0000177352
:28C:00000/002
```
![image](https://user-images.githubusercontent.com/270571/41457317-8f0c6012-7083-11e8-9bd3-452ac2acfb50.png)

Example code:
```
import mt940
import coloredlogs


coloredlogs.install(level='DEBUG')
mt940.parse('test.stl')
```

**Comment by mncoon** [comment]
Hi! 
Thanks for your quick answer. The dots are standing for many transaction lines, so they are not real in the file. But we will checkt the file with your example code.

**Comment by WoLpH** [comment]
I was guessing that but the behaviour is similar, if the following line is not recognized as a separate tag it will be appended to the previous one :)
