### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by spoetnik** [WoLpH/mt940#7]
Thanks again for the release of a mt940 parser for Python.

Could you please give a code snippet of how to use this library?
How do I get the details of a Transaction? (booking date, id, amount, reference etc...)
Thanks!

**Comment by WoLpH** [comment]
Due to the lack of standards in the format the API doesn't have a uniform standard either...

Some properties are always available luckily (although I can't put any guarantees on them being filled correctly for all cases), I'll add some docs for you :)

Short version, read `transaction.__dict__` for all available properties :)
For example: `transaction.date`

**Comment by WoLpH** [comment]
Almost done with a large rewrite with proper docs and more consistent
workings :)

Stay tuned ;)

It's all in the better docs branch:
https://github.com/WoLpH/mt940/tree/feature/better_docs

**Comment by WoLpH** [comment]
Ok, I've released a new version with better docs.

Actually... it's pretty much a full rewrite, hope you like it ;)
http://mt940.readthedocs.org/en/latest/

**Comment by spoetnik** [comment]
Cool, thanks a lot!

**Comment by davidzwa** [comment]
@WoLpH , thanks for your effort into developing this library! I am currently using it with success, but I have trouble extracting more transaction and transactions data than enabled by the DEFAULT_PROCESSORS variable.
I have tried to follow your example, which alters the processors argument in the transactions constructor, but I'm not able to understand all the different types of keys in this dictionary. 

Can you add more examples in the documentation to add for example certain the before and after balance of a transaction? (You call this pre and post, right? I am not familiar with accountancy lingo ;) )

**Comment by WoLpH** [comment]
> I have tried to follow your example, which alters the **processors** argument in the **Transactions** model constructor, but I'm not able to understand all the different types of keys in this dictionary. 
Most of the data simply comes from straight from the mt940 standard. I'm not entirely sure what all of them mean but I found this site quite helpful: http://www.sepaforcorporates.com/swift-for-corporates/account-statement-mt940-file-format-overview/

> Can you add more examples in the documentation to add for example certain the _before_ and _after balance_ of a transaction as a **Balance** type?
Sure, can you tell me what you are trying to do? I'll see if I can make a useful example out of it :)

> You call this _pre_ and _post_, right? I am not familiar with accountancy lingo 😉
The _pre_ and _post_ is simply short for prefix and postfix (suffix). Which is derived from the latin pre- and post. So no accountancy lingo there, I actually know very little about accountancy and simply created this library because I wanted to create an app to get statistics about my bank account ;)
