### ISSUE TITLE
Status and Fund code , when Currency ends with a D 

### ISSUE THREAD

**Issue by NickSwann** [wolph/mt940#90]
Hi, 

I believe I have found a bug in the RegEx for the tag 61 status code. 

On occasions when the currency also ends in a D, I'm getting CD, DD in the status group, and nothing in the fund code 

I have tested the regex at due to this section` (?P<status>[A-Z]?[DC])` the [A-Z] is matching status code and the [DC] then matches the fund code

**Comment by WoLpH** [comment]
Yeah... that could be problematic indeed. I've made it rather flexible since I wasn't sure I could find a complete list of status codes. Since many banks create their own standard with their own weirdness this is still possible even with the list you created.

But I'm all for making it tighter :)

I'm similarly swamped with work unfortunately though :(
