### ISSUE TITLE
Single "account_identification" field

### ISSUE THREAD

**Issue by ssebastian90** [wolph/mt940#95]
Hi WoLpH,

Although I have multiple statement account present in the file, parser returns the last of them.
Is it possible to insert field (25: ) into transactions ? 
I saw another issue closed without result.

Example:
:20:0003478756
:25:ACXXXXXX000000XXXXXX1

:20:0003478756
:25:ACXXXXXX000000XXXXXX3

account_identification=ACXXXXXX000000XXXXXX3

Thank you

**Comment by anushaeranda** [comment]
I also same issue. can we sort out this problem

**Comment by wolph** [comment]
This has been fixed in the latest release :)

https://github.com/wolph/mt940/blob/302379b58add0673e579e09bee8971e53cfbbabb/mt940_tests/self-provided/account_identification.yml#L3-L4


https://github.com/wolph/mt940/blob/302379b58add0673e579e09bee8971e53cfbbabb/mt940_tests/self-provided/account_identification.sta#L1-L2
